sudo: false
language: python
python:
  - 2.6
  - 2.7
env:
  - FLASK=0.10.1
install: pip install -r requirements/test.txt
script:
  - "pep8 --show-source --show-pep8 --max-line-length=85 --benchmark api/*.py" 
