sudo: false
language: python
python:
  - 2.6
  - 2.7
env:
  - FLASK=0.10.1
  - FLASK=0.9
install:
  - pip install -q FLASK==$FLASK
  - pip install -q -r requirements.txt
  - pip install -q -e .
script:
  - python setup.py test
